### ISSUE TITLE
Inconsistent number of proposal with paper

### ISSUE THREAD

**Issue by Junpliu** [idansc/fga#4]
Hi, thank you for your great work. The number of proposals is 36 in paper, but why does pretrained feature file contain 37 proposals?
Is the last (37th) dimension additional or extra? Or, how could I identify the 36 proposals?

**Comment by idansc** [comment]
The code here is a refactored version. There are slight changes from the details reported in the paper. Those small nuances shouldn't affect the correctness, i.e., you can use 36 proposals if you wish.
