### ISSUE TITLE
Direct download links - curlwget not accessible

### ISSUE THREAD

**Issue by sharanyarc96** [idansc/fga#5]
You can use [curlwget](https://chrome.google.com/webstore/detail/curlwget/jmocjfidanebdlinpbcdkcmgdifblncg?hl=en)

_Originally posted by @idansc in https://github.com/idansc/fga/issues/3#issuecomment-723393025_

Regarding your previous response: I am no longer able to access curlwget. Do you have any suggestions for alternative ways of downloading the data?

**Comment by idansc** [comment]
I can see if I can upload it to S3, but It will take some time. Meanwhile, I'd download the features from https://github.com/vmurahari3/visdial-bert
It's the same features; make sure the images' indices align with the other preprocessed files.

**Comment by idansc** [comment]
Hi, 
curlwget is back: 
https://chrome.google.com/webstore/detail/curlwget/dgcfkhmmpcmkikfmonjcalnjcmjcjjdn
