### ISSUE TITLE
Hello, when I run trian.py, an error is reported as shown in the figure below. How can I solve it?

### ISSUE THREAD

**Issue by kelikeli** [idansc/fga#7]
![image](https://user-images.githubusercontent.com/34790058/121356298-4ca8ac80-c963-11eb-82b6-41209ff9561f.png)

**Comment by idansc** [comment]
My code copies run files to a new location (see L339-344 in train.py). The training process is not affected by this code. 
So feel free to comment out L344.

**Comment by kelikeli** [comment]
Ok, thank you very much for your reply. I will try to run it again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月14日(星期一) 下午3:01
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [idansc/fga] Hello, when I run trian.py, an error is reported as shown in the figure below. How can I solve it? (#7)





 
My code copies run files to a new location (see L339-344 in train.py). The training process is not affected by this code.
 So feel free to comment out L344.
